### ISSUE TITLE
Please add timestamp to Transaction_filter

### ISSUE THREAD

**Issue by modersohn** [juanmardefago/loopring-subgraph-v2#2]
AFAICS there is currently no way to query (account) transactions for a specific timeframe.

I've got a use-case where I want to export a CSV of all transactions of a given account (doing taxes etc.). Imagine I've accumulated 10s of thousands of transactions over the years - how can I get only those transactions from say, last year?

Thanks for considering this.

**Comment by Brechtpd** [comment]
Hey, if you go to the [loopring explorer](https://explorer.loopring.io ) and go to your account page, at the bottom you can export all your transactions to a CSV file. Each transaction also contains when it was verified, so you should be able to filter on that there.

**Comment by modersohn** [comment]
Sorry if I wasn't clear. This is not about using loopring explorer (which will **always** export **all** transactions, so you need to filter them afterwards manually).

I want to write a tool/website/whatever - using the graph that this repository is about, i.e. https://thegraph.com/hosted-service/subgraph/loopring/loopring - and retrieve transactions for a specific timeframe **only**.

This is currently not possible, because "Transaction_filter" does not offer anything to filter by block.timeframe.

**Comment by Montspy** [comment]
@modersohn 
I found the following in the docs (using it here for `TransactionNFT_filter`, but it is documented for `Transaction_filter` too

You can access the `Block_filter.timestamp*` fields via the `block_` field for `TransactionNFT_filter` and `Transaction_filter`
```gql
query collectionTransactions {
    transactionNFTs(
        orderBy: id
        orderDirection: asc
        first: 25
        skip: 0
        where: {
            nfts_: {
                token: "0x1d006a27bd82e10f9194d30158d91201e9930420"
            }, 
            block_: {
                timestamp_gte: 1664582400,
                timestamp_lte: 1667260800
            },
            typename: TradeNFT
        }
    ) {
        block { timestamp }
        id
        typename
        slots(first: 2, skip: 0) {
            account { id, address }
            balance
        }
        ... on TradeNFT {
            realizedNFTPrice
            feeSeller
            feeBuyer
            token {
                symbol
                decimals
            }
        }
    }
}
```

**Comment by Montspy** [comment]
Although it is prone to sporadic errors in my testing #3

**Comment by modersohn** [comment]
@Montspy back when I opened this issue, I didn't know about the `Block_height` query parameters. But we've been using those for Lexplorer for quite a while now. I'm not aware of sporadic errors - but that doesn't mean they don't occur.

I'm closing this issue now as `Block_height` is the intended way of querying the graph and extra date filters aren't necessary.
